### ISSUE TITLE
Should sameAs really be called sameAs?

### ISSUE THREAD

**Issue by michmech** [oasis-tcs/lexidma#100]
(Submitted by David Lindemann)

One suggestion: Isn’t skos:exactMatch better than owl:sameAs for expressing that a POS tag matches to a lexinfo or OLiA or whatever URI? owl:sameAs means that two entities are exactly the same, including all statements made about them (=including all triples with one of the two as subjects). That is not the case here, so I think skos:exactMatch is better; that just claims that two URI represent entities describing the same thing, allowing different statements for the two. I think this distinction is important for machine reasoning. For example, in Wikdiata, owl:sameAs is used for internal redirects, when a user merges items (for the machine: instead of looking at entity A, you can look at entity B, and assume that every single statement about B is true for A as well).

**Comment by jmccrae** [comment]
Yes, probably exactMatch has better semantics as there may be structural restrictions that we do not want to import

**Comment by DavidFatDavidF** [comment]
REQUIRED implementation of `sameAs` in RDF is `exactMatch`
Agreed in meeting on 4th April 2024
