### ISSUE TITLE
Doing more with examples

### ISSUE THREAD

**Issue by michmech** [oasis-tcs/lexidma#104]
(Submitted by Jonatan Steller, talking about his DMLex implementation in TYPO3)

There is one aspect that I think should not go  
unnoticed as it illustrates the neat design of DMLex. The lexicographic  
resources we produce at the Academy of Sciences and Literature Mainz  
often contain historical examples, as in the case of field names or  
names of historical persons. To accommodate this, we simply added  
properties like "period", "locationRelation" and "agentRelation" to the  
existing "Examples" class and allowed for an "example" property in the  
"Entry" class in addition to the "Sense" class. Furthermore, we needed  
frequency data for multiple countries to both "Entry" and "Sense" and  
were able to just add a respective class and property as a sort-of  
custom module. This is to highlight that I have become very fond of the  
modular design of the spec because implementers like me may need this  
sort of flexibility.

**Comment by jmccrae** [comment]
The request here is to allow for extra properties to be included easily? We should probably document something about user-specific extensions as this is in practice very important for the adoption of models such as this

**Comment by michmech** [comment]
We do say in section "2 Conformance" that "DMLex Instances MAY contain custom extensions" etc. and I think this is sufficient.
