### ISSUE TITLE
Finalize URIs for RDF articles

### ISSUE THREAD

**Issue by jmccrae** [oasis-tcs/lexidma#106]
The spec is currently using the following URI for the RDF ontology

http://www.oasis-open.org/to-be-confirmed/dmlex#

We need to confirm the final URI and update the spec before publication

@DavidFatDavidF this is not for the 2nd public review but to be handled in one of the pre-final versions

**Comment by DavidFatDavidF** [comment]
I think we should address this as part of the normative machine readable artifacts issues.. I would raise this under one of those issues, or mark this one as derived from one of them

**Comment by DavidFatDavidF** [comment]
This issue is derrived from #93 and as such will be addressed as part of 2nd public review CRM

**Comment by DavidFatDavidF** [comment]
IMHO the ontology should use this
`https://docs.oasis-open.org/lexidma/dmlex/v1.0/`
as the root URI and any artifatcts can be actually placed there as part of the subsequent reviews and would make it also publicly availbale with an alaways current URI/IRI for each subsequent approval step

**Comment by jmccrae** [comment]
So probably we will add `dmlex.rdf` as a file to this folder and so have

`https://docs.oasis-open.org/lexidma/dmlex/v1.0/dmlex.rdf`

Alternatively we could add a subfolder and have the URL as 

`https://docs.oasis-open.org/lexidma/dmlex/v1.0/RDF/dmlex`

Do you know if OASIS servers support content negotiation or at least symbolic links?

**Comment by DavidFatDavidF** [comment]
I raised the issue with OASIS Admin, so that we can agree on the ideal URI/IRI solution before launching the 3rd public review
I suggest that we create the following structure for machine readable artifacts:
```
https://docs.oasis-open.org/lexidma/dmlex/v1.0/schemas/
https://docs.oasis-open.org/lexidma/dmlex/v1.0/schemas/RDF/
https://docs.oasis-open.org/lexidma/dmlex/v1.0/schemas/XML/
https://docs.oasis-open.org/lexidma/dmlex/v1.0/schemas/JSON/
https://docs.oasis-open.org/lexidma/dmlex/v1.0/schemas/informativeCopiesOf3rdPartySchemas/
https://docs.oasis-open.org/lexidma/dmlex/v1.0/schemas/informativeCopiesOf3rdPartySchemas/w3c/
..
[https://docs.oasis-open.org/lexidma/dmlex/v1.0/schemas/[other potential subfolders]

```

**Comment by DavidFatDavidF** [comment]
On Github the artifacts will be in schemas folder, sibling to `../dmlex/specification/`
Decided 2024-03-28
