### ISSUE TITLE
XML Schema mandates order of elements but serialization description does not

### ISSUE THREAD

**Issue by jmccrae** [oasis-tcs/lexidma#117]
Either

* The schemas should be revised by the use of `<xs:all>` or similar (although this seems very problematic for XSD, see https://stackoverflow.com/questions/2290360/xsd-how-to-allow-elements-in-any-order-any-number-of-times)
* The specification should clearly state all ordering rules

**Comment by jmccrae** [comment]
Relates to #93

**Comment by michmech** [comment]
Good point.

In the XML serialisation, order matters for XML elements that implement model-level types that have a model-level `listingOrder` property. This property is actually implemented _by_ the elements' order.

For all other XML elements, order doesn't really matter. But then you'd end up with e.g. senses containing a mixture of child elements for whom order matters (`<example>` etc.) and child elements for whom order doesn't matter (`<indicator>` etc.). That seems complex. Maybe the XML serialisation would become simpler if we simply said that child elements are supposed to always be in the order in which they are listed in the spec?
