### ISSUE TITLE
Can `entry` be a root of an XML document?

### ISSUE THREAD

**Issue by jmccrae** [oasis-tcs/lexidma#118]
The spec states 

"a valid DMLex XML document is one where either a lexicographic Resource or an entry is the document element"

and then

* The top-level `lexicographicResource` object is implemented as an XML element.
* All other objects are implemented as XML attributes of their parents

This seems contradictory

**Comment by michmech** [comment]
Let's say this issue follows from issue #93.

**Comment by michmech** [comment]
True. I have changed the wording (in the 'Design Principles' section of the XML serialisation), it now says:

> - The top-level lexicographicResource and entry object types are implemented as XML elements.
> - All other object types and their properties are implemented as XML attributes of their parents, unless [...]
