### ISSUE TITLE
Should `collocateMarker` have a uniqueness constraints?

### ISSUE THREAD

**Issue by jmccrae** [oasis-tcs/lexidma#122]
Currently `collocateMarker` has a uniqueness constraint on the `lemma` field. This means the following is invalid according to the spec

```xml
<entry id="frog">
  <headword>frog</headword>
  <example>
    <text><collocateMarker lemma="dog">dogs</collocateMarker> used to sit on <headwordMarker>frogs</headwordMarker> and now <collocateMarker lemma="dog">dogs</collocateMarker> sit on logs</text>
  </example>
</entry>
```

This is an error in my opinion.

Relates to the implementation of #97

**Comment by michmech** [comment]
True. The `lemma` shouldn't be part of a `collocateMarker`'s uniqueness constraint. 

I think it's logical that the `collocateMarker'`s `startIndex` and `endIndex` should be its uniqueness constraint: it should be prohibited to have two collocate markers on the same thing (on the same substring).

I have made this change in the prose.

**Comment by jmccrae** [comment]
If we make `startIndex` and `endIndex` the unique properties, we should also apply this to all other markers, right?

**Comment by michmech** [comment]
You're right!
