### ISSUE TITLE
OASIS editorial comments for the 3rd public review draft

### ISSUE THREAD

**Issue by DavidFatDavidF** [oasis-tcs/lexidma#134]
These editorial comments by OASIS Admin Paul Knight were copied from OASIS JIRA ticket
https://issues.oasis-open.org/browse/TCADMIN-4510
These need to be addressed as part of the 3rd public review milestone

1. Vojtěch Kovář should be added as Editor to the list in the "Citation format" block on front pages.

2. In the small "Notices" section on the front pages, the right parenthesis characters should be removed (two places, following hyperlinked text.

3. The unnecessary "Related work" section should be completely removed from the front pages.

4. In Section 3.4, Example 3, in the PDF file, the first line extends beyond the page margin.

5. Apparently the two JSON schema files were renamed, with ".schema" added before ".json", so they are "dmlex_no-crosslingual.schema.json" and  "dmlex.schema.json" - while the links to those files in Appendix C still point to the old names - https://docs.oasis-open.org/lexidma/dmlex/v1.0/csd03/schemas/JSON/dmlex.json and [...]JSON/dmlex_no-crosslingual.json.

6. The directory and file [...]/schemas/informativeCopiesOf3rdPartySchemas/w3c/xml.xsd are not present, so the link from the Normative reference [XML namespace] is broken. (Probably better to just remove that link, since there is already a link to the W3C site's file.)

summary of bad links:
https://docs.oasis-open.org/lexidma/dmlex/v1.0/csd03/schemas/informativeCopiesOf3rdPartySchemas/w3c/xml.xsd
(w3c directory is not present)

BAD: https://docs.oasis-open.org/lexidma/dmlex/v1.0/csd03/schemas/JSON/dmlex.json
filename: https://docs.oasis-open.org/lexidma/dmlex/v1.0/csd03/schemas/JSON/dmlex.schema.json

BAD: https://docs.oasis-open.org/lexidma/dmlex/v1.0/csd03/schemas/JSON/dmlex_no-crosslingual.json
filename: https://docs.oasis-open.org/lexidma/dmlex/v1.0/csd03/schemas/JSON/dmlex_no-crosslingual.schema.json

**Comment by DavidFatDavidF** [comment]
@jmccrae assigned to fix example formatting

**Comment by DavidFatDavidF** [comment]
@mjakubicek assigned to fix JSON schema files naming including mentions from appendices etc.

**Comment by DavidFatDavidF** [comment]
@DavidFatDavidF tp remove mentions of the local copy of w3c xml schema that we will not use
JSON schema related bad links should be resolved by @mjakubicek by fixing the file names

**Comment by DavidFatDavidF** [comment]
Fixed 1.-3., and 6. with a direct commit including editorial progression stuff (pub entities and change tracking)

**Comment by mjakubicek** [comment]
David you never pushed these changes -- they are only in your repository; and meanwhile incompatible. Also, there are some typos (double ".pdf" at the top of the commit, lowercase "draft" for CSD04 change). Best if you could fix this yourself.

**Comment by DavidFatDavidF** [comment]
Closed with real time edits by @mjakubicek
