### ISSUE TITLE
missing text tag admissions in XML serializations

### ISSUE THREAD

**Issue by DavidFatDavidF** [oasis-tcs/lexidma#137]
Section 5.1 does not list which of the <text> tags can take `<headwordMarker>`, `<collocateMarker>` and `<placeholderMarker>`

**Comment by jmccrae** [comment]
I think this is my mistake. We can close this with no changes!

**Comment by michmech** [comment]
Section 5.1. *does* actually have this information. Every time an element is defined there which can contain text marked up with any of these, it says so, for example like this: "If implementing the Annotation Module `<text>` can contain a
mixture of plain text, `<headwordMarker>` elements and `<collocateMarker>` elements." (from section 5.1.4.6).

So, yes, a non-issue, no change needed.
