### ISSUE TITLE
Clarification for headword marker

### ISSUE THREAD

**Issue by DavidFatDavidF** [oasis-tcs/lexidma#138]
Example translations can be headword markers, but they are translations so cannot actually contain the headword. Perhaps the intention is to indicate which word is the translation as follows:

```xml
<example>
  <text>The <headwordMarker>cat</headwordMarker> sits on the <collocateMarker>mat</collocateMarker>.</text>
  <exampleTranslation langCode="es">
     <text>El <headwordMarker>gato</headwordMarker> se sienta en la <collocateMarker>alfombra</collocateMarker>.</text>
  </exampleTranslation>
</example>
```

Still it seems a bit difficult and unnecessary, when exampleTranslation could be a plain string.

**Comment by jmccrae** [comment]
Perhaps add this as another example

**Comment by michmech** [comment]
Yes, that is the intention.

We say at the model level (section 4.4.7) that a `headwordMarker` "[m]arks up a substring [...] which corresponds to the headword (or to a translation of the headword)", and then Example A.1.22 shows an example of exactly that.

So, I think this intention is communicated quite clearly as is, no additional examples are needed.

Suggest to close this as a non-issue.
