### ISSUE TITLE
JSON examples missing

### ISSUE THREAD

**Issue by DavidFatDavidF** [oasis-tcs/lexidma#53]
Many JSON examples are missing (Ex 10, 26)

**Comment by DavidFatDavidF** [comment]
@michmech to implement by January 3, 2024

**Comment by michmech** [comment]
- Examples 10 and 26 look like this: `"..."` and they actually *aren’t* placeholders or anything, they are actual JSON examples. They show that the object in question is to be implemented in JSON as a string.
- There are a total of 4 JSON examples like this in the entire document. I have added “Implemented as a string” to them to make it clear that this not an error.

Will close automatically when pull request #75 is merged.
