### ISSUE TITLE
4.3.2 uniqueness Constraint in linking module clarification

### ISSUE THREAD

**Issue by DavidFatDavidF** [oasis-tcs/lexidma#56]
I don't understand the uniqueness constraint in 4.3.2. Can this be made clearer?

**Comment by michmech** [comment]
4.3.2 defines the data type `relation`.

The idea behind the uniqueness constraints there is that there can never be two relations with the same type and the same members. For example, if one relation says that A and B are synonyms, there is not allowed to exist another relation that says the same thing.

But I agree that this is perhaps not obvious from how the constraint is stated in the text. And it’s not very water-right either. I think the uniqueness "key" of a relation should be determined from its type and from the `memberID` properties of its members.

Or if that’s too complex, then perhaps we should give up on the idea altogether. If people want to have two relations that say the same thing, then let them have it. After all, we’re not prohibiting people from having two identical or almost identical entries in a lexicographic resource either.

**Comment by DavidFatDavidF** [comment]
Decision Dec 12:
Those restriction will be dropped with a Note explaining caveats
