### ISSUE TITLE
Inconsistent serializations of Controlled vocabularies module's "inflectedFormTag"

### ISSUE THREAD

**Issue by DavidFatDavidF** [oasis-tcs/lexidma#60]
The definition of InflectedFormTag (and several others) seems to list different properties in the serializations

**Comment by michmech** [comment]
I have had a look and I don’t see the problem. It seems to me that the properties of `inflectedFormTag` at model level, and the properties/attributes of its serializations, are perfectly consistent (apart from differences in pluralization, for that see issue #70). What am I missing?

**Comment by jmccrae** [comment]
I think I misread the text... it seems fine. 

There is a tiny typo though `dmlex:forHeadwods`

**Comment by DavidFatDavidF** [comment]
overtaken by events, see the solution for #55
