### ISSUE TITLE
Define which elements have `id`

### ISSUE THREAD

**Issue by jmccrae** [oasis-tcs/lexidma#65]
It is not defined in the standard which elements have an `id`.

Some elements cannot have `id` (`partOfSpeech` and `label`) as this would not be represent-able in JSON and RDF serialization

Issue arose during implementation of #61

**Comment by DavidFatDavidF** [comment]
We explain non-normatively in the abstract model why some objects have ids in the abstract model and some serializations, we will not be adding new ids to the model, we will have this as an implementation Note in the abstract data model
@michmech to implement by January 3

**Comment by michmech** [comment]
- Actually, *no* objects have IDs at the model level.
- In the JSON, XML and NVH serializations, there are three object types that can have IDs: entries, senses and collocate markers. The purpose and the only function of the IDs is to allow them to appear as members of relations. I have updated the text to say that these three object types have IDs only if implementing the Annotations module.

Will close automatically when pull request #75 is merged.
