### ISSUE TITLE
Member has a `member_id` which is not its ID

### ISSUE THREAD

**Issue by jmccrae** [oasis-tcs/lexidma#66]
This property's name is confusing. Can we change it to something like `ref` to indicate it is the reference not the ID of the member?

Issue arose during implementation of #61

**Comment by DavidFatDavidF** [comment]
Rename "member_id" to "ref" and make clear that it references objects, referencing mechanism is serialization specific
@michmech to implement by January 3, 2024

**Comment by michmech** [comment]
- Done at model level
- Done in serializations
- Done in the “Examples” section

Will close automatically when pull request #75 is merged.
