### ISSUE TITLE
`obverseListingOrder` is mandatory but missing in examples

### ISSUE THREAD

**Issue by jmccrae** [oasis-tcs/lexidma#67]
The property `obverseListingOrder` is mandatory for `member`s but is not used in examples.

I think this should probably not be mandatory

Issue blocks implementation of #61

**Comment by jmccrae** [comment]
Make `obverseListingOrder` optional (agreed 20/12)

**Comment by michmech** [comment]
- Done at model level
- Done in serializations

Will close automatically when pull request #75 is merged.
