### ISSUE TITLE
`role` is mandatory on `memberType` but not `member`

### ISSUE THREAD

**Issue by jmccrae** [oasis-tcs/lexidma#68]
This is means relations have a defined `memberType` that is not used. It should probably be optional as it is in several examples

Blocking implementation of #61

**Comment by jmccrae** [comment]
Make `role` optional on `memberType` (agreed 20/12)

**Comment by michmech** [comment]
- Done at model level
- Done in serializations

Will close automatically when pull request #75 is merged.
