### ISSUE TITLE
Editorial preparation of the csd02 progression

### ISSUE THREAD

**Issue by DavidFatDavidF** [oasis-tcs/lexidma#76]
@michmech and @jmccrae please provide descriptions of changes made in response to the 1st public review in 
the file
`../specification/RevieChangeTracking/csd01.xml`

@michmech and @jmccrae please also review and finalize 
`../admin/Simple-comment-resolution-log_DMLex_1.0_csd01.xls`

**Comment by michmech** [comment]
Done. I've listed all changes that I consider 'major' (which is actually almost all of them).

@jmccrae: I've covered changes you've made, so if you're happy, you don't need to do anything. :-)
