### ISSUE TITLE
Various editorial issues

### ISSUE THREAD

**Issue by michmech** [oasis-tcs/lexidma#79]
(Submitted by Paul Knight)

During publication of the files for CSD02, the OASIS staff noted some items which the LEXIDMA TC may wish to consider.

These items are numbered for convenience, not ranked in any particular order of importance.

1.  "Committee" is misspelled on the front page (PDF only - corrected in the HTML during publication). This also affects the "Citation format" text towards the end of the front pages.

2. XML parsing error for the file /conformance/conformance.xml. (&version; undefined - inside a warning message).

3. The informative text for Appendix C mentions "OM" without any definition.  (maybe Object Model ??)

4. The initial sentence in Appendix F is essentially obsolete, and could be rewritten or simply removed.

5. In the Normative References (Appendix B.2), the additional text " at https://docs.oasis-open.org/lexidma/dmlex/v1.0/csd02/schemas/informativeCopiesOf3rdPartySchemas/w3c/xml.xsd in this distribution" should either be removed or made correct by including the target file.

6. Section 1.2 lists serialization languages which appear to be hyperlinked to empty targets. It appears that the intent is to link to the references in Appendix B. These hyperlinks should be properly instantiated.

**Comment by DavidFatDavidF** [comment]
1. Updated entities in in dbgent.mod, including misspelled stage name
2. This is a component document and, as standalone, the entity ;&version doesn't  track. This doesn't cause any issue on publication as the entity gets resolved during the build process 
3. Appendix C placeholder text will be replaced with provided validation artifacts before progression to csd03
4. Placeholder sentence removed. @michmech please create and link a document describing csd02 changes
5. The file will be provided as part as XML validation artifacts
6. Pointer refs fixed

**Comment by michmech** [comment]
> Placeholder sentence removed. @michmech please create and link a document describing csd02 changes

This is now done (in commit ecd7e0f).
