### ISSUE TITLE
Only one headword per entry

### ISSUE THREAD

**Issue by michmech** [oasis-tcs/lexidma#83]
(Submitted by Jan Niestadt)

I can see that sometimes you'd want these to be separate entries, but in other cases I feel putting them in the main entry would be simpler, especially if the variants will never actually be processed or displayed as separate entries, just shown as a list in the main entry. Again, this is only my opinion, but it would be nice if the standard was flexible enough to support both approaches, allowing each project to choose what works best for them.

**Comment by jmccrae** [comment]
Multiple headwords is common enough in dictionaries, especially historical dictionaries, but I also think that it creates a lot of issues for indexing and querying
