### ISSUE TITLE
URIs for entries and senses

### ISSUE THREAD

**Issue by michmech** [oasis-tcs/lexidma#97]
(Submitted by Louis Cotgrove)

Can there be an option for a uri tag at the entry and sense levels? I can foresee use cases (such as an abbreviated version of a resource that links to the full text, or for citations), where this would be useful. I see this might be covered by the linking module, but this seems more complicated for me as a potential user

**Comment by jmccrae** [comment]
I think this would be great. I am in favour of URIs and IDs on all elements
