### ISSUE TITLE
What’s the point of homograph number?

### ISSUE THREAD

**Issue by michmech** [oasis-tcs/lexidma#99]
(Submitted by David Lindemann)

Something strange from the Wikibase point of view is to have a “homograph number” at entry level, which in fact only informs you that there are homographs (if lemmata without homographs in the lemma list don’t have “1” but just no homograph number to make clear they are alone), but not how many, or which ones. I understand that this is something coming from digitized dictionaries. In Wikibase, one would instead of numbering homographs claim which ones are the homograph entries, and link them using a dedicated property, just like this is done on Wikidata.

**Comment by jmccrae** [comment]
I see David's point, but in practice homograph numbers of indicate the importance of each homograph for the definition, so it would have display implications
